const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Arr.Acts.Insert,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.ScriptsInEvents.Homemanager_Event3_Act11,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Exps.Get
	];
};
self.C3_JsPropNameTable = [
	{far_background_element: 0},
	{mid_background_element: 0},
	{foreground_element: 0},
	{far_background_element2: 0},
	{pauseBG: 0},
	{landing_screen: 0},
	{Fade: 0},
	{FadeOutBGHome: 0},
	{FadeOutBGGameplay: 0},
	{RemoveObjectWall: 0},
	{GameOverBG: 0},
	{APIBG: 0},
	{loadingText: 0},
	{change_lanes_button: 0},
	{Coins_lettering: 0},
	{Tween: 0},
	{game_over_lettering: 0},
	{game_over_screen_background: 0},
	{home: 0},
	{leaderboard: 0},
	{pause: 0},
	{pause_lettering: 0},
	{pause_screen_background: 0},
	{play: 0},
	{restart: 0},
	{teleport_button: 0},
	{CoinCountText: 0},
	{GameTime: 0},
	{HomePlay: 0},
	{HomeLeaderBoard: 0},
	{GameOverHome: 0},
	{GameOverLeaderboard: 0},
	{music_note: 0},
	{coin_Normal: 0},
	{CoinUpsideDown: 0},
	{Cupid: 0},
	{cupid_teleport_anim: 0},
	{cupid_reappear_anim: 0},
	{bone_bat_: 0},
	{dove_: 0},
	{Devil: 0},
	{crate_: 0},
	{grave_: 0},
	{Touch: 0},
	{Keyboard: 0},
	{Audio: 0},
	{AJAX: 0},
	{JSON: 0},
	{ScoreContainerArray: 0},
	{Browser: 0},
	{teleportTouchCount: 0},
	{jumpTouchCount: 0},
	{isPlayerUp: 0},
	{isPlayerOnSky: 0},
	{coinCounter: 0},
	{coinXLastPosition: 0},
	{graveLastXposition: 0},
	{crateLastXposition: 0},
	{batXLastPosition: 0},
	{doveXLastPosition: 0},
	{devilXLastPosition: 0},
	{isPlayerDie: 0},
	{boneBatFrequncey: 0},
	{crateFrequncey: 0},
	{devilFrquncey: 0},
	{doveFrquncey: 0},
	{graveFrquncey: 0},
	{gameTime: 0},
	{gameIncreaseTime: 0},
	{devilMoveFrquncey: 0},
	{doveMoveFrequncey: 0},
	{batMoveFrquncey: 0},
	{tempScore: 0},
	{previousScore: 0},
	{XYZ: 0},
	{LOP: 0},
	{QUT: 0},
	{sigv1: 0},
	{scoreArrayContainer2: 0},
	{scoreArrayContanierIndex: 0},
	{fetchKey: 0},
	{gameOver: 0},
	{gameStarted: 0},
	{coinRandom: 0},
	{devilSpawnCount: 0},
	{bgSpeed: 0},
	{gamePause: 0},
	{sound: 0},
	{isFirstTime: 0},
	{leaderBoardURL: 0}
];

self.InstanceType = {
	far_background_element: class extends self.ISpriteInstance {},
	mid_background_element: class extends self.ISpriteInstance {},
	foreground_element: class extends self.ISpriteInstance {},
	far_background_element2: class extends self.ISpriteInstance {},
	pauseBG: class extends self.ISpriteInstance {},
	landing_screen: class extends self.ISpriteInstance {},
	FadeOutBGHome: class extends self.ISpriteInstance {},
	FadeOutBGGameplay: class extends self.ISpriteInstance {},
	RemoveObjectWall: class extends self.ISpriteInstance {},
	GameOverBG: class extends self.ISpriteInstance {},
	APIBG: class extends self.ISpriteInstance {},
	loadingText: class extends self.ITextInstance {},
	change_lanes_button: class extends self.ISpriteInstance {},
	Coins_lettering: class extends self.ISpriteInstance {},
	game_over_lettering: class extends self.ISpriteInstance {},
	game_over_screen_background: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	leaderboard: class extends self.ISpriteInstance {},
	pause: class extends self.ISpriteInstance {},
	pause_lettering: class extends self.ISpriteInstance {},
	pause_screen_background: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	teleport_button: class extends self.ISpriteInstance {},
	CoinCountText: class extends self.ITextInstance {},
	GameTime: class extends self.ITextInstance {},
	HomePlay: class extends self.ISpriteInstance {},
	HomeLeaderBoard: class extends self.ISpriteInstance {},
	GameOverHome: class extends self.ISpriteInstance {},
	GameOverLeaderboard: class extends self.ISpriteInstance {},
	music_note: class extends self.ISpriteInstance {},
	coin_Normal: class extends self.ISpriteInstance {},
	CoinUpsideDown: class extends self.ISpriteInstance {},
	Cupid: class extends self.ISpriteInstance {},
	cupid_teleport_anim: class extends self.ISpriteInstance {},
	cupid_reappear_anim: class extends self.ISpriteInstance {},
	bone_bat_: class extends self.ISpriteInstance {},
	dove_: class extends self.ISpriteInstance {},
	Devil: class extends self.ISpriteInstance {},
	crate_: class extends self.ISpriteInstance {},
	grave_: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	ScoreContainerArray: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {}
}